steps:
    # build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/adl-service', '.']
      # push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/adl-service']
      # Deploy container image to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
          [
              'beta',
              'run',
              'deploy',
              'adl-service',
              '--image',
              'gcr.io/$PROJECT_ID/adl-service',
              '--region',
              '[REGION]',
              '--platform',
              '[PLATFORM]',
              '--quiet',
          ]
images:
    - gcr.io/$PROJECT_ID/adl-service
